SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE
WHERE
    EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3 -- MONTH(DATE_OF_BIRTH)
    AND GENDER = 'W'
    AND TLNO IS NOT NULL
ORDER BY
    1 ASC;
