SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS P
    JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC;

-- GROUP BY 사용시 주의점!!
--
-- GROUP BY를 쓰면, SELECT절의 모든 칼럼은 아래 둘 중 하나여야만 함:
--
-- 1. `GROUP BY`에 명시된 칼럼
-- 2. `SUM`, `AVG`, `MIN`, `MAX` 등의 집계함수로 감싼 칼럼
