WITH CTE AS (
    SELECT
        PARENT_ID,
        COUNT(*) AS CNT
    FROM
        ECOLI_DATA
    GROUP BY
        PARENT_ID
)

SELECT
    E.ID,
    COALESCE(CTE.CNT, 0) AS CHILD_COUNT
FROM
    ECOLI_DATA AS E
    LEFT JOIN CTE ON E.ID = CTE.PARENT_ID
ORDER BY
    E.ID ASC;
