WITH CTE AS (
    SELECT
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
            ELSE '4Q'
        END AS QUARTER,
        ID
    FROM
        ECOLI_DATA
) -- CTE 끝에는 세미콜론이 안 붙는다! 괄호만 닫고 끝임

SELECT
    CTE.QUARTER AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM
    ECOLI_DATA AS D
    JOIN CTE ON D.ID = CTE.ID
GROUP BY
    CTE.QUARTER
ORDER BY
    1 ASC;
