SELECT
    P.PRODUCT_CODE,
    SUM(P.PRICE * S.SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE AS S
    JOIN PRODUCT AS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    SUM(P.PRICE * S.SALES_AMOUNT) DESC,
    P.PRODUCT_CODE ASC;
