WITH CTE AS (
    SELECT
        COUNT(DISTINCT USER_ID) AS CNT
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
)

SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / CNT, 1) AS PURCHASED_RATIO
FROM
    USER_INFO AS I
    JOIN ONLINE_SALE AS S ON I.USER_ID = S.USER_ID
    CROSS JOIN CTE
WHERE
    YEAR(I.JOINED) = 2021
GROUP BY
    YEAR(S.SALES_DATE),
    MONTH(S.SALES_DATE)
ORDER BY
    YEAR(S.SALES_DATE) ASC,
    MONTH(S.SALES_DATE) ASC;
