SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR, -- 어차피 표준대로 쓸 일 없는데, SQL 표준 집착을 버리자
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA
ORDER BY
    1 ASC,
    2 ASC;

-- 윈도우 함수 적용한 두번째 풀이 (YEAR 대신 EXTRACT 사용)
--
-- SELECT
--     EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
--     (MAX(SIZE_OF_COLONY) OVER (PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
--     ID
-- FROM
--     ECOLI_DATA
-- ORDER BY
--     1 ASC,
--     2 ASC;
--
-- 첫 풀이 (서브쿼리)
--
-- SELECT
--     EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
--     MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
--     ID
-- FROM
--     ECOLI_DATA AS D
--     JOIN (
--         SELECT
--             EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
--             MAX(SIZE_OF_COLONY) AS MAX_SIZE
--         FROM
--             ECOLI_DATA
--         GROUP BY
--             EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
--     ) AS TBL ON EXTRACT(YEAR FROM D.DIFFERENTIATION_DATE) = TBL.YEAR
-- ORDER BY
--     1 ASC,
--     2 ASC;
