SELECT
    O.ANIMAL_ID,
    O.NAME
FROM
    ANIMAL_INS AS I
    JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY
    O.DATETIME - I.DATETIME DESC -- DATETIME 타입의 필드끼리 덧셈이나 뺄셈 가능
LIMIT
    2;
