SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) >= 7
ORDER BY
    2 DESC,
    1 DESC;

-- 오답 쿼리 (DATE 타입이 숫자로 쓰일 땐 자동으로 YYYYMMDD 형태로 변환된다! 따라서, 그냥 빼버리면 일수 차이가 아니라 YYYYMMDD 값의 차이가 된다..)
--
-- SELECT
--     CAR_ID,
--     ROUND(AVG(END_DATE - START_DATE + 1), 1) AS AVERAGE_DURATION
-- FROM
--     CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY
--     CAR_ID
-- HAVING
--     ROUND(AVG(END_DATE - START_DATE + 1), 1) >= 7
-- ORDER BY
--     2 DESC,
--     1 DESC;
