SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM
    BOOK_SALES AS S
    LEFT JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
    LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID -- 안전하게 둘 다 LEFT JOIN 썼는데, 그냥 JOIN 써도 정답 처리된다
WHERE
    S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC,
    B.CATEGORY DESC;
